In [94]:
import requests
import pandas as pd
import json

In [95]:
# the query protein
query = "CADM4_HUMAN"

In [ ]:
# Function that adds '_HUMAN' afterfix to column values
def add_suffix_human(value):
    return value + '_HUMAN'

In [105]:
# Function that takes a ppi dataframe and outputs from two columns only one column with the interactor

def get_interactors_for_target(df, col_a, col_b, target_protein):
    def get_interactors(row):
        if row[col_a] == target_protein:
            return row[col_b]
        elif row[col_b] == target_protein:
            return row[col_a]
        else:
            return None
    df['interactor_of_' + target_protein] = df.apply(get_interactors, axis = 1)
    
    return df

In [10]:
# Function that uses the UniProt-API to get the ProteinID or either the Protein name

def convert_protein_ID_Name(uniprotID_or_name): # e.g. can be P19320 or VCAM1_HUMAN
    
    uniprot_api_url = "https://rest.uniprot.org/uniprotkb" 
    format = "json"
    uniprot_request_url = f"{uniprot_api_url}/{uniprotID_or_name}?format={format}"
    uniprot_json = requests.get(uniprot_request_url).text
    
    uniprot_dict = json.loads(uniprot_json) # convering to dictionary

    if "_" in uniprotID_or_name:
        value = uniprot_dict["primaryAccession"]
    else:
        value = uniprot_dict['uniProtkbId']
        
    return (value)

# example
id_or_name = convert_protein_ID_Name(query)
print(id_or_name)

Q8NFZ8

In [96]:
# Extracting the data from the BioGRID API

# BioGRID Access Key: caf14dfd9a0b7be447d282c322b8362e

biogrid_api_url = "https://webservice.thebiogrid.org/interactions"

geneList = [query]

params = {
    "accesskey": "caf14dfd9a0b7be447d282c322b8362e", # need to request
    "format": "json",
    "geneList": geneList,
    "taxId": 9606, # human
    "max": 10000
}

response = requests.get(biogrid_api_url, params=params)
biogrid_interactions = response.json()

print(biogrid_interactions)

biogrid_data = {}
for interaction_id, interaction in biogrid_interactions.items():
    biogrid_data[interaction_id] = interaction
    biogrid_data[interaction_id]["INTERACTION_ID"] = interaction_id
    
# loading into dataframe

biogrid_df = pd.DataFrame.from_dict(biogrid_data, orient="index")

columns = [
    "INTERACTION_ID",
    "ENTREZ_GENE_A",
    "ENTREZ_GENE_B",
    "OFFICIAL_SYMBOL_A",
    "OFFICIAL_SYMBOL_B",
    "EXPERIMENTAL_SYSTEM",
    "PUBMED_ID",
    "PUBMED_AUTHOR",
    "THROUGHPUT",
    "QUALIFICATIONS"]

biogrid_df = biogrid_df[columns]

biogrid_df.head(5)

{'600990': {'BIOGRID_INTERACTION_ID': 600990, 'ENTREZ_GENE_A': '1454', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 107838, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': 'RP1-5O6.1', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'CSNK1E', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'CKIepsilon|HCKIE', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Two-hybrid', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Vinayagam A (2011)', 'PUBMED_ID': 21900206, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '-', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': '-', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '601286': {'BIOGRID_INTERACTION_ID': 601286, 'ENTREZ_GENE_A': '1780', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 108118, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'DYNC1I1', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'DNCI1|DNCIC1', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Two-hybrid', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Vinayagam A (2011)', 'PUBMED_ID': 21900206, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '-', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': '-', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '1051917': {'BIOGRID_INTERACTION_ID': 1051917, 'ENTREZ_GENE_A': '6472', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 112368, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'SHMT2', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'GLYA|HEL-S-51e|SHMT', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-RNA', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Castello A (2012)', 'PUBMED_ID': 22658674, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '-', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': '-', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '1196008': {'BIOGRID_INTERACTION_ID': 1196008, 'ENTREZ_GENE_A': '253012', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 128949, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': 'UNQ305/PRO346', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'HEPACAM2', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'MIKI', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2015)', 'PUBMED_ID': 26186194, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.949667574', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 1.0 HEK 293T cells CompPASS score = 0.949667574, threshold = 0.75. Quantitative scores calculated by CompPASS-Plus (Huttlin et al. Cell, 2015, PMID: 26186194).|See BioPlex Interactome for details (https://bioplex.hms.harvard.edu/index.php).|This data has also been reanalyzed as part of BioPlex 2.0 (PMID: 28514442) and BioPlex 3.0 (PMID: 33961781). Only scores from within BioPlex 1.0 (PMID: 26186194) should be compared directly.', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '2232293': {'BIOGRID_INTERACTION_ID': 2232293, 'ENTREZ_GENE_A': '29785', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 118915, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': 'UNQ891/PRO1906', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'CYP2S1', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': '-', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2017)', 'PUBMED_ID': 28514442, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.998999752', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 2.0 HEK 293T cells CompPASS score = 0.998999752, threshold = 0.75. Quantitative scores calculated by CompPASS-Plus (Huttlin et al. Cell, 2015, PMID: 26186194).|See BioPlex Interactome for details (https://bioplex.hms.harvard.edu/index.php).|This data has also been reanalyzed as part of BioPlex 3.0 (PMID: 33961781) and may be re-scored from BioPlex 1.0 (PMID: 26186194). Only scores from within BioPlex 2.0 (PMID: 28514442) should be compared directly.', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '2257453': {'BIOGRID_INTERACTION_ID': 2257453, 'ENTREZ_GENE_A': '253012', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 128949, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': 'UNQ305/PRO346', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'HEPACAM2', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'MIKI', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2017)', 'PUBMED_ID': 28514442, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.91175748', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 2.0 HEK 293T cells CompPASS score = 0.91175748, threshold = 0.75. Quantitative scores calculated by CompPASS-Plus (Huttlin et al. Cell, 2015, PMID: 26186194).|See BioPlex Interactome for details (https://bioplex.hms.harvard.edu/index.php).|This data has also been reanalyzed as part of BioPlex 3.0 (PMID: 33961781) and may be re-scored from BioPlex 1.0 (PMID: 26186194). Only scores from within BioPlex 2.0 (PMID: 28514442) should be compared directly.', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '2269448': {'BIOGRID_INTERACTION_ID': 2269448, 'ENTREZ_GENE_A': '969', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 107407, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'CD69', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'AIM|BL-AC/P26|CLEC2C|EA1|GP32/28|MLR-3', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2017)', 'PUBMED_ID': 28514442, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.791109841', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 2.0 HEK 293T cells CompPASS score = 0.791109841, threshold = 0.75. Quantitative scores calculated by CompPASS-Plus (Huttlin et al. Cell, 2015, PMID: 26186194).|See BioPlex Interactome for details (https://bioplex.hms.harvard.edu/index.php).|This data has also been reanalyzed as part of BioPlex 3.0 (PMID: 33961781) and may be re-scored from BioPlex 1.0 (PMID: 26186194). Only scores from within BioPlex 2.0 (PMID: 28514442) should be compared directly.', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '2494593': {'BIOGRID_INTERACTION_ID': 2494593, 'ENTREZ_GENE_A': '6047', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 111974, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': 'RES4-26', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'RNF4', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'SLX5|SNURF', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Kumar R (2017)', 'PUBMED_ID': 29180619, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '-', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': '-', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '2548673': {'BIOGRID_INTERACTION_ID': 2548673, 'ENTREZ_GENE_A': '4893', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 110952, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': 'RP5-1000E10.2', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'NRAS', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'ALPS4|CMNS|N-ras|NCMS|NRAS1|NS6', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Proximity Label-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Kovalski JR (2019)', 'PUBMED_ID': 30639242, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '-', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioID', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '2802380': {'BIOGRID_INTERACTION_ID': 2802380, 'ENTREZ_GENE_A': '43740574', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 4383871, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': 'GU280_gp08', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'ORF7b', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'SARS-CoV2 ORF7b|SARS-CoV-2 ORF7b|7b|NS7B_SARS2|PRO_0000449799', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Proximity Label-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Laurent E (2020)', 'PUBMED_ID': 888800000082, 'ORGANISM_A': 2697049, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '-', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioID|To facilitate data interpretation, an arbitrary filter was used to filter out human prey proteins connected to 8 or more viral bait proteins. High confidence interactors had an FDR < 0.01 and were detected by 7 or fewer viral bait proteins.', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '2872233': {'BIOGRID_INTERACTION_ID': 2872233, 'ENTREZ_GENE_A': '7157', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 113010, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'TP53', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'BCC7|LFS1|P53|TRP53', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Negative Genetic', 'EXPERIMENTAL_SYSTEM_TYPE': 'genetic', 'PUBMED_AUTHOR': 'Liu C (2019)', 'PUBMED_ID': 30862715, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'Low Throughput', 'QUANTITATION': '-', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'CRISPR GI screen|Cell Line:  hESC|Experimental Setup: Drug Exposure: Cisplatin CHEBI:27899|GIST: Mono-phenotypic suppressing genetic interaction|KO of hit genes re-sensitizes TP53 KO cells to cisplatin|Library: GeckoV2|Significance Threshold: p<0.01', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '2888675': {'BIOGRID_INTERACTION_ID': 2888675, 'ENTREZ_GENE_A': '11156', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 116327, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'PTP4A3', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'PRL-3|PRL-R|PRL3', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Positive Genetic', 'EXPERIMENTAL_SYSTEM_TYPE': 'genetic', 'PUBMED_AUTHOR': 'Funato Y (2020)', 'PUBMED_ID': 32918875, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'Low Throughput', 'QUANTITATION': '-', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {'1181653': {'ONTOLOGY_TERM_ID': 'PATO:0000169', 'NAME': 'viability', 'TYPE_ID': 4, 'TYPE_NAME': 'Unspecified', 'QUALIFIERS': {}, 'FLAG': 'P', 'DESC': "An organismal quality inhering in a bearer or a population by virtue of the bearer's disposition to survive and develop normally or the number of surviving individuals in a given population.", 'ID': 9503, 'ONTOLOGY_CATEGORY': 'phenotype'}, '1181652': {'ONTOLOGY_TERM_ID': 'HP:0001507', 'NAME': 'Growth abnormality', 'TYPE_ID': 4, 'TYPE_NAME': 'Unspecified', 'QUALIFIERS': {}, 'FLAG': 'P', 'DESC': '-', 'ID': 127875, 'ONTOLOGY_CATEGORY': 'phenotype'}}, 'QUALIFICATIONS': 'CRISPR GI screen|Cell Line: HEK293|Experimental Setup: Exposure to alkaline stress|GIST: A-phenotypic positive genetic interaction|Library: Geckov2|Significance Threshold: [FDR] < 0.05', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '3030171': {'BIOGRID_INTERACTION_ID': 3030171, 'ENTREZ_GENE_A': '29785', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 118915, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': 'UNQ891/PRO1906', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'CYP2S1', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': '-', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2021)', 'PUBMED_ID': 33961781, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.843617171', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 3.0 HEK 293T cells CompPASS score = 0.843617171, threshold = 0.75. Quantitative scores are calculated by CompPASS-Plus (Huttlin et al. Cell 2015, PMID: 26186194). The 0.75 threshold represents the top 2% of scores in HEK293T.|This data may be re-scored from BioPlex 1.0 (PMID: 26186194) and BioPlex 2.0 (PMID: 28514442). Only scores from within the same cell line in BioPlex 3.0 (PMID: 33961781) should be compared directly. For comparison of HEK293T and HCT116 interaction networks with relaxed threshold = 0.1, see BioPlex Interactome (https://bioplex.hms.harvard.edu/index.php).', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '3033915': {'BIOGRID_INTERACTION_ID': 3033915, 'ENTREZ_GENE_A': '2051', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 108365, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'EPHB6', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'HEP', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2021)', 'PUBMED_ID': 33961781, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.896157773', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 3.0 HEK 293T cells CompPASS score = 0.896157773, threshold = 0.75. Quantitative scores are calculated by CompPASS-Plus (Huttlin et al. Cell 2015, PMID: 26186194). The 0.75 threshold represents the top 2% of scores in HEK293T.|This data may be re-scored from BioPlex 1.0 (PMID: 26186194) and BioPlex 2.0 (PMID: 28514442). Only scores from within the same cell line in BioPlex 3.0 (PMID: 33961781) should be compared directly. For comparison of HEK293T and HCT116 interaction networks with relaxed threshold = 0.1, see BioPlex Interactome (https://bioplex.hms.harvard.edu/index.php).', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '3038619': {'BIOGRID_INTERACTION_ID': 3038619, 'ENTREZ_GENE_A': '57678', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 121707, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': 'RP11-426E5.2', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'GPAM', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'GPAT|GPAT1', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2021)', 'PUBMED_ID': 33961781, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.993451518', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 3.0 HEK 293T cells CompPASS score = 0.993451518, threshold = 0.75. Quantitative scores are calculated by CompPASS-Plus (Huttlin et al. Cell 2015, PMID: 26186194). The 0.75 threshold represents the top 2% of scores in HEK293T.|This data may be re-scored from BioPlex 1.0 (PMID: 26186194) and BioPlex 2.0 (PMID: 28514442). Only scores from within the same cell line in BioPlex 3.0 (PMID: 33961781) should be compared directly. For comparison of HEK293T and HCT116 interaction networks with relaxed threshold = 0.1, see BioPlex Interactome (https://bioplex.hms.harvard.edu/index.php).', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '3044141': {'BIOGRID_INTERACTION_ID': 3044141, 'ENTREZ_GENE_A': '199731', 'ENTREZ_GENE_B': '23181', 'BIOGRID_ID_A': 128268, 'BIOGRID_ID_B': 116793, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'CADM4', 'OFFICIAL_SYMBOL_B': 'DIP2A', 'SYNONYMS_A': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'SYNONYMS_B': 'C21orf106|DIP2', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2021)', 'PUBMED_ID': 33961781, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.859369602', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 3.0 HEK 293T cells CompPASS score = 0.859369602, threshold = 0.75. Quantitative scores are calculated by CompPASS-Plus (Huttlin et al. Cell 2015, PMID: 26186194). The 0.75 threshold represents the top 2% of scores in HEK293T.|This data may be re-scored from BioPlex 1.0 (PMID: 26186194) and BioPlex 2.0 (PMID: 28514442). Only scores from within the same cell line in BioPlex 3.0 (PMID: 33961781) should be compared directly. For comparison of HEK293T and HCT116 interaction networks with relaxed threshold = 0.1, see BioPlex Interactome (https://bioplex.hms.harvard.edu/index.php).', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '3047452': {'BIOGRID_INTERACTION_ID': 3047452, 'ENTREZ_GENE_A': '969', 'ENTREZ_GENE_B': '199731', 'BIOGRID_ID_A': 107407, 'BIOGRID_ID_B': 128268, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'CD69', 'OFFICIAL_SYMBOL_B': 'CADM4', 'SYNONYMS_A': 'AIM|BL-AC/P26|CLEC2C|EA1|GP32/28|MLR-3', 'SYNONYMS_B': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2021)', 'PUBMED_ID': 33961781, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.868330548', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 3.0 HEK 293T cells CompPASS score = 0.868330548, threshold = 0.75. Quantitative scores are calculated by CompPASS-Plus (Huttlin et al. Cell 2015, PMID: 26186194). The 0.75 threshold represents the top 2% of scores in HEK293T.|This data may be re-scored from BioPlex 1.0 (PMID: 26186194) and BioPlex 2.0 (PMID: 28514442). Only scores from within the same cell line in BioPlex 3.0 (PMID: 33961781) should be compared directly. For comparison of HEK293T and HCT116 interaction networks with relaxed threshold = 0.1, see BioPlex Interactome (https://bioplex.hms.harvard.edu/index.php).', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '3047877': {'BIOGRID_INTERACTION_ID': 3047877, 'ENTREZ_GENE_A': '199731', 'ENTREZ_GENE_B': '201627', 'BIOGRID_ID_A': 128268, 'BIOGRID_ID_B': 128398, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': '-', 'OFFICIAL_SYMBOL_A': 'CADM4', 'OFFICIAL_SYMBOL_B': 'DENND6A', 'SYNONYMS_A': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'SYNONYMS_B': 'AFI1A|FAM116A', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2021)', 'PUBMED_ID': 33961781, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.96936719', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 3.0 HEK 293T cells CompPASS score = 0.96936719, threshold = 0.75. Quantitative scores are calculated by CompPASS-Plus (Huttlin et al. Cell 2015, PMID: 26186194). The 0.75 threshold represents the top 2% of scores in HEK293T.|This data may be re-scored from BioPlex 1.0 (PMID: 26186194) and BioPlex 2.0 (PMID: 28514442). Only scores from within the same cell line in BioPlex 3.0 (PMID: 33961781) should be compared directly. For comparison of HEK293T and HCT116 interaction networks with relaxed threshold = 0.1, see BioPlex Interactome (https://bioplex.hms.harvard.edu/index.php).', 'TAGS': '-', 'SOURCEDB': 'BIOGRID'}, '3060610': {'BIOGRID_INTERACTION_ID': 3060610, 'ENTREZ_GENE_A': '199731', 'ENTREZ_GENE_B': '9397', 'BIOGRID_ID_A': 128268, 'BIOGRID_ID_B': 114794, 'SYSTEMATIC_NAME_A': '-', 'SYSTEMATIC_NAME_B': 'RP11-455B2.2', 'OFFICIAL_SYMBOL_A': 'CADM4', 'OFFICIAL_SYMBOL_B': 'NMT2', 'SYNONYMS_A': 'IGSF4C|NECL4|Necl-4|TSLL2|synCAM4', 'SYNONYMS_B': '-', 'EXPERIMENTAL_SYSTEM': 'Affinity Capture-MS', 'EXPERIMENTAL_SYSTEM_TYPE': 'physical', 'PUBMED_AUTHOR': 'Huttlin EL (2021)', 'PUBMED_ID': 33961781, 'ORGANISM_A': 9606, 'ORGANISM_B': 9606, 'THROUGHPUT': 'High Throughput', 'QUANTITATION': '0.958379092', 'MODIFICATION': '-', 'ONTOLOGY_TERMS': {}, 'QUALIFICATIONS': 'BioPlex 3.0 HEK 293T cells CompPASS score = 0.958379092, threshold = 0.75. Quantitative scores are calculated by CompPASS-Plus (Huttlin

,INTERACTION_ID,ENTREZ_GENE_A,ENTREZ_GENE_B,OFFICIAL_SYMBOL_A,OFFICIAL_SYMBOL_B,EXPERIMENTAL_SYSTEM,PUBMED_ID,PUBMED_AUTHOR,THROUGHPUT,QUALIFICATIONS
600990,600990,1454,199731,CSNK1E,CADM4,Two-hybrid,21900206,Vinayagam A (2011),High Throughput,-
601286,601286,1780,199731,DYNC1I1,CADM4,Two-hybrid,21900206,Vinayagam A (2011),High Throughput,-
1051917,1051917,6472,199731,SHMT2,CADM4,Affinity Capture-RNA,22658674,Castello A (2012),High Throughput,-
1196008,1196008,253012,199731,HEPACAM2,CADM4,Affinity Capture-MS,26186194,Huttlin EL (2015),High Throughput,BioPlex 1.0 HEK 293T cells CompPASS score = 0....
2232293,2232293,29785,199731,CYP2S1,CADM4,Affinity Capture-MS,28514442,Huttlin EL (2017),High Throughput,BioPlex 2.0 HEK 293T cells CompPASS score = 0....

In [108]:
# Cleaning the dataframe

# filter out the columns that are needed
biogrid_df_filter = biogrid_df[[    'OFFICIAL_SYMBOL_A', 
                                    'OFFICIAL_SYMBOL_B', 
                                    'EXPERIMENTAL_SYSTEM', 
                                    'PUBMED_ID',
                                    'PUBMED_AUTHOR']]

# adding 'HUMAN' afterfix to the column values
biogrid_df_filter[['OFFICIAL_SYMBOL_A', 'OFFICIAL_SYMBOL_B']] = biogrid_df_filter[['OFFICIAL_SYMBOL_A', 'OFFICIAL_SYMBOL_B']].apply(add_suffix_human)

# renaming column headers
df_biogrid_final = biogrid_df_filter.rename(columns= {  'OFFICIAL_SYMBOL_A': 'biogrid_interactor_a', 
                                                        'OFFICIAL_SYMBOL_B': 'biogrid_interactor_b',
                                                        'EXPERIMENTAL_SYSTEM': 'biogrid_method',
                                                        'PUBMED_ID': 'biogrid_pubID',
                                                        'PUBMED_AUTHOR': 'biogrid_publication'})

# get one column, only the interactor of the query
df_biogrid = get_interactors_for_target(df_biogrid_final, 'biogrid_interactor_a', 'biogrid_interactor_b', query)

df_biogrid.head(5)


# df_biogrid_final.head(5)

/tmp/ipykernel_231037/2593118694.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  biogrid_df_filter[['OFFICIAL_SYMBOL_A', 'OFFICIAL_SYMBOL_B']] = biogrid_df_filter[['OFFICIAL_SYMBOL_A', 'OFFICIAL_SYMBOL_B']].apply(add_suffix_human)

,biogrid_interactor_a,biogrid_interactor_b,biogrid_method,biogrid_pubID,biogrid_publication,interactor_of_CADM4_HUMAN
600990,CSNK1E_HUMAN,CADM4_HUMAN,Two-hybrid,21900206,Vinayagam A (2011),CSNK1E_HUMAN
601286,DYNC1I1_HUMAN,CADM4_HUMAN,Two-hybrid,21900206,Vinayagam A (2011),DYNC1I1_HUMAN
1051917,SHMT2_HUMAN,CADM4_HUMAN,Affinity Capture-RNA,22658674,Castello A (2012),SHMT2_HUMAN
1196008,HEPACAM2_HUMAN,CADM4_HUMAN,Affinity Capture-MS,26186194,Huttlin EL (2015),HEPACAM2_HUMAN
2232293,CYP2S1_HUMAN,CADM4_HUMAN,Affinity Capture-MS,28514442,Huttlin EL (2017),CYP2S1_HUMAN

In [109]:
# Extracting the data from the IntAct API using PSCIQUIC

intact_api_url = "http://www.ebi.ac.uk/Tools/webservices/psicquic/intact/webservices"

version = "current"
method = "interactor"
protein = query
format = "tab25"

intact_request_url = f"{intact_api_url}/{version}/search/{method}/{protein}?format={format}"

intact_raw_data = requests.get(intact_request_url).text

print(intact_raw_data)

uniprotkb:A8MVW5-2	uniprotkb:Q8NFZ8	intact:EBI-21700103	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:a8mvw52(display_long)|uniprotkb:HEPACAM2(gene name)|psi-mi:HEPACAM2(display_short)|uniprotkb:MIKI(gene name synonym)|uniprotkb:UNQ305/PRO346(orf name)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0007"(anti tag coimmunoprecipitation)	Huttlin et al. (2017)	pubmed:28514442|doi:10.1038/nature22366|imex:IM-25778	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-21700110|imex:IM-25778-9205	intact-miscore:0.35
uniprotkb:Q07108	uniprotkb:Q8NFZ8	intact:EBI-2836595|ensembl:ENSP00000228434.3	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:cd69_human(display_long)|uniprotkb:CD69(gene name)|psi-mi:CD69(display_short)|uniprotkb:CLEC2C(gene name synonym)|uniprotkb:Activation inducer molecule(gene name synonym)|uniprotkb:BL-AC/P26(gene name synonym)|uniprotkb:C-type lectin domain family 2 member C(gene name synonym)|uniprotkb:EA1(gene name synonym)|uniprotkb:Early T-cell activation antigen p60(gene name synonym)|uniprotkb:GP32/28(gene name synonym)|uniprotkb:Leukocyte surface antigen Leu-23(gene name synonym)|uniprotkb:MLR-3(gene name synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0007"(anti tag coimmunoprecipitation)	Huttlin et al. (2017)	pubmed:28514442|doi:10.1038/nature22366|imex:IM-25778	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-21551241|imex:IM-25778-3489	intact-miscore:0.35
uniprotkb:Q96SQ9-2	uniprotkb:Q8NFZ8	intact:EBI-21537560	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:q96sq92(display_long)|uniprotkb:CYP2S1(gene name)|psi-mi:CYP2S1(display_short)|uniprotkb:UNQ891/PRO1906(orf name)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0007"(anti tag coimmunoprecipitation)	Huttlin et al. (2017)	pubmed:28514442|doi:10.1038/nature22366|imex:IM-25778	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-21623270|imex:IM-25778-7645	intact-miscore:0.35
uniprotkb:P60033	uniprotkb:Q8NFZ8	intact:EBI-712921|uniprotkb:P18582|uniprotkb:Q5U0J6|ensembl:ENSP00000263645.5	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:cd81_human(display_long)|uniprotkb:26 kDa cell surface protein TAPA-1(gene name synonym)|uniprotkb:Target of the antiproliferative antibody 1(gene name synonym)|uniprotkb:Tetraspanin-28(gene name synonym)|uniprotkb:CD81(gene name)|psi-mi:CD81(display_short)|uniprotkb:TAPA1(gene name synonym)|uniprotkb:TSPAN28(gene name synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0006"(anti bait coimmunoprecipitation)	Palor et al. (2020)	imex:IM-28053|pubmed:32900848	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-25645944|imex:IM-28053-1	intact-miscore:0.35
uniprotkb:P60033	uniprotkb:Q8NFZ8	intact:EBI-712921|uniprotkb:P18582|uniprotkb:Q5U0J6|ensembl:ENSP00000263645.5	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:cd81_human(display_long)|uniprotkb:26 kDa cell surface protein TAPA-1(gene name synonym)|uniprotkb:Target of the antiproliferative antibody 1(gene name synonym)|uniprotkb:Tetraspanin-28(gene name synonym)|uniprotkb:CD81(gene name)|psi-mi:CD81(display_short)|uniprotkb:TAPA1(gene name synonym)|uniprotkb:TSPAN28(gene name synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0006"(anti bait coimmunoprecipitation)	Palor et al. (2020)	imex:IM-28053|pubmed:32900848	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-25646004|imex:IM-28053-5	intact-miscore:0.35
uniprotkb:P60033	uniprotkb:Q8NFZ8	intact:EBI-712921|uniprotkb:P18582|uniprotkb:Q5U0J6|ensembl:ENSP00000263645.5	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:cd81_human(display_long)|uniprotkb:26 kDa cell surface protein TAPA-1(gene name synonym)|uniprotkb:Target of the antiproliferative antibody 1(gene name synonym)|uniprotkb:Tetraspanin-28(gene name synonym)|uniprotkb:CD81(gene name)|psi-mi:CD81(display_short)|uniprotkb:TAPA1(gene name synonym)|uniprotkb:TSPAN28(gene name synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0006"(anti bait coimmunoprecipitation)	Palor et al. (2020)	imex:IM-28053|pubmed:32900848	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-25646019|imex:IM-28053-7	intact-miscore:0.35
uniprotkb:P60033	uniprotkb:Q8NFZ8	intact:EBI-712921|uniprotkb:P18582|uniprotkb:Q5U0J6|ensembl:ENSP00000263645.5	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:cd81_human(display_long)|uniprotkb:26 kDa cell surface protein TAPA-1(gene name synonym)|uniprotkb:Target of the antiproliferative antibody 1(gene name synonym)|uniprotkb:Tetraspanin-28(gene name synonym)|uniprotkb:CD81(gene name)|psi-mi:CD81(display_short)|uniprotkb:TAPA1(gene name synonym)|uniprotkb:TSPAN28(gene name synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0006"(anti bait coimmunoprecipitation)	Palor et al. (2020)	imex:IM-28053|pubmed:32900848	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-25646036|imex:IM-28053-9	intact-miscore:0.35
uniprotkb:P13569	uniprotkb:Q8NFZ8	intact:EBI-349854|uniprotkb:Q20BG8|uniprotkb:Q20BH2|uniprotkb:Q2I0A1|uniprotkb:Q2I102|ensembl:ENSP00000003084.6	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:cftr_human(display_long)|uniprotkb:CFTR(gene name)|psi-mi:CFTR(display_short)|uniprotkb:ABCC7(gene name synonym)|uniprotkb:cAMP-dependent chloride channel(gene name synonym)|uniprotkb:ATP-binding cassette sub-family C member 7(gene name synonym)|uniprotkb:Channel conductance-controlling ATPase(gene name synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:1314"(proximity-dependent biotin identification)	Chevalier et al. (2022)	imex:IM-29540|pubmed:36012204	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:2364"(proximity)	psi-mi:"MI:0469"(IntAct)	intact:EBI-40230404|imex:IM-29540-9	intact-miscore:0.27
uniprotkb:P13569	uniprotkb:Q8NFZ8	intact:EBI-349854|uniprotkb:Q20BG8|uniprotkb:Q20BH2|uniprotkb:Q2I0A1|uniprotkb:Q2I102|ensembl:ENSP00000003084.6	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:cftr_human(display_long)|uniprotkb:CFTR(gene name)|psi-mi:CFTR(display_short)|uniprotkb:ABCC7(gene name synonym)|uniprotkb:cAMP-dependent chloride channel(gene name synonym)|uniprotkb:ATP-binding cassette sub-family C member 7(gene name synonym)|uniprotkb:Channel conductance-controlling ATPase(gene name synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:1314"(proximity-dependent biotin identification)	Chevalier et al. (2022)	imex:IM-29540|pubmed:36012204	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:2364"(proximity)	psi-mi:"MI:0469"(IntAct)	intact:EBI-34588902|imex:IM-29540-1	intact-miscore:0.27
uniprotkb:O14649	uniprotkb:Q8NFZ8	intact:EBI-8559445|intact:MINT-1645466|uniprotkb:Q53SU2|ensembl:ENSP00000306275.3	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:kcnk3_human(display_long)|uniprotkb:KCNK3(gene name)|psi-mi:KCNK3(display_short)|uniprotkb:TASK(gene name synonym)|uniprotkb:TASK1(gene name synonym)|uniprotkb:Acid-sensitive potassium channel protein TASK-1(gene name synonym)|uniprotkb:"TWIK-related acid-sensitive K(+) channel 1"(gene name synonym)|uniprotkb:Two pore potassium channel KT3.1(gene name synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:1314"(proximity-dependent biotin identification)	Chevalier et al. (2022)	imex:IM-29540|pubmed:36012204	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:2364"(proximity)	psi-mi:"MI:0469"(IntAct)	intact:EBI-40212731|imex:IM-29540-3	intact-miscore:0.27
uniprotkb:P13569	uniprotkb:Q8NFZ8	intact:EBI-349854|uniprotkb:Q20BG8|uniprotkb:Q20BH2|uniprotkb:Q2I0A1|uniprotkb:Q2I102|ensembl:ENSP00000003084.6	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:cftr_human(display_long)|uniprotkb:CFTR(gene name)|psi-mi:CFTR(display_short)|uniprotkb:ABCC7(gene name synonym)|uniprotkb:cAMP-dependent chloride channel(gene name synonym)|uniprotkb:ATP-binding cassette sub-family C member 7(gene name synonym)|uniprotkb:Channel conductance-controlling ATPase(gene name synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:1314"(proximity-dependent biotin identification)	Chevalier et al. (2022)	imex:IM-29540|pubmed:36012204	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:2364"(proximity)	psi-mi:"MI:0469"(IntAct)	intact:EBI-40232309|imex:IM-29540-11	intact-miscore:0.27
uniprotkb:P10636-8	uniprotkb:Q8NFZ8	intact:EBI-366233|ensembl:ENSP00000303214.7|ensembl:ENSP00000460965.1|ensembl:ENSP00000477703.1|ensembl:ENSP00000484491.1|ensembl:ENSP00000487819.1|ensembl:ENSP00000515600.1|intact:EBI-7470331|intact:MINT-134477|intact:EBI-7470384|intact:EBI-7638179|intact:EBI-7638125|intact:EBI-7638230|intact:EBI-7638364|intact:EBI-7961077|intact:EBI-7470086|intact:EBI-7637965|intact:EBI-7638329|intact:EBI-7470156|intact:EBI-7470185|intact:EBI-7470243|intact:EBI-7638049|intact:EBI-7470111|intact:EBI-7637861	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:p10636-8(display_long)|uniprotkb:Tau-4(isoform synonym)|uniprotkb:MAPT(gene name)|psi-mi:MAPT(display_short)|uniprotkb:MAPTL(gene name synonym)|uniprotkb:MTBT1(gene name synonym)|uniprotkb:TAU(gene name synonym)|uniprotkb:Neurofibrillary tangle protein(gene name synonym)|uniprotkb:Paired helical filament-tau(gene name synonym)|uniprotkb:2N4R(isoform synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0007"(anti tag coimmunoprecipitation)	Tracy et al. (2022)	pubmed:35063084|imex:IM-29773	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-46419579|imex:IM-29773-22	intact-miscore:0.35
uniprotkb:P10636-8	uniprotkb:Q8NFZ8	intact:EBI-366233|ensembl:ENSP00000303214.7|ensembl:ENSP00000460965.1|ensembl:ENSP00000477703.1|ensembl:ENSP00000484491.1|ensembl:ENSP00000487819.1|ensembl:ENSP00000515600.1|intact:EBI-7470331|intact:MINT-134477|intact:EBI-7470384|intact:EBI-7638179|intact:EBI-7638125|intact:EBI-7638230|intact:EBI-7638364|intact:EBI-7961077|intact:EBI-7470086|intact:EBI-7637965|intact:EBI-7638329|intact:EBI-7470156|intact:EBI-7470185|intact:EBI-7470243|intact:EBI-7638049|intact:EBI-7470111|intact:EBI-7637861	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:p10636-8(display_long)|uniprotkb:Tau-4(isoform synonym)|uniprotkb:MAPT(gene name)|psi-mi:MAPT(display_short)|uniprotkb:MAPTL(gene name synonym)|uniprotkb:MTBT1(gene name synonym)|uniprotkb:TAU(gene name synonym)|uniprotkb:Neurofibrillary tangle protein(gene name synonym)|uniprotkb:Paired helical filament-tau(gene name synonym)|uniprotkb:2N4R(isoform synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0007"(anti tag coimmunoprecipitation)	Tracy et al. (2022)	pubmed:35063084|imex:IM-29773	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-46421644|imex:IM-29773-23	intact-miscore:0.35
uniprotkb:P10636-8	uniprotkb:Q8NFZ8	intact:EBI-366233|ensembl:ENSP00000303214.7|ensembl:ENSP00000460965.1|ensembl:ENSP00000477703.1|ensembl:ENSP00000484491.1|ensembl:ENSP00000487819.1|ensembl:ENSP00000515600.1|intact:EBI-7470331|intact:MINT-134477|intact:EBI-7470384|intact:EBI-7638179|intact:EBI-7638125|intact:EBI-7638230|intact:EBI-7638364|intact:EBI-7961077|intact:EBI-7470086|intact:EBI-7637965|intact:EBI-7638329|intact:EBI-7470156|intact:EBI-7470185|intact:EBI-7470243|intact:EBI-7638049|intact:EBI-7470111|intact:EBI-7637861	intact:EBI-7129521|ensembl:ENSP00000222374.1|uniprotkb:B2R7L5|intact:UNK-5523414|uniprotkb:Q9Y4A4	psi-mi:p10636-8(display_long)|uniprotkb:Tau-4(isoform synonym)|uniprotkb:MAPT(gene name)|psi-mi:MAPT(display_short)|uniprotkb:MAPTL(gene name synonym)|uniprotkb:MTBT1(gene name synonym)|uniprotkb:TAU(gene name synonym)|uniprotkb:Neurofibrillary tangle protein(gene name synonym)|uniprotkb:Paired helical filament-tau(gene name synonym)|uniprotkb:2N4R(isoform synonym)	psi-mi:cadm4_human(display_long)|uniprotkb:CADM4(gene name)|psi-mi:CADM4(display_short)|uniprotkb:IGSF4C(gene name synonym)|uniprotkb:NECL4(gene name synonym)|uniprotkb:TSLL2(gene name synonym)|uniprotkb:Immunoglobulin superfamily member 4C(gene name synonym)|uniprotkb:Nectin-like protein 4(gene name synonym)|uniprotkb:TSLC1-like protein 2(gene name synonym)	psi-mi:"MI:0007"(anti tag coimmunoprecipitation)	Tracy et al. (2022)	pubmed:35063084|imex:IM-29773	taxid:9606(human)|taxid:9606(Homo sapiens)	taxid:9606(human)|taxid:9606(Homo sapiens)	psi-mi:"MI:0914"(association)	psi-mi:"MI:0469"(IntAct)	intact:EBI-46423222|imex:IM-29773-25	intact-miscore:0.35

In [110]:
# Getting the data into a pandas df

# Split each row into a list of columns based on PSI-MI TAB 2.5 format
intact_columns = ['Unique identifier for interactor A', 
                    'Unique identifier for interactor B', 
                    'Alternative identifier for interactor A', 
                    'Alternative identifier for interactor B', 
                    'Aliases for A', 
                    'Aliases for B', 
                    'Interaction detection methods', 
                    'First author', 
                    'Identifier of the publication', 
                    'NCBI Taxonomy identifier for interactor A', 
                    'NCBI Taxonomy identifier for interactor B', 
                    'Interaction types', 
                    'Source databases', 
                    'Interaction identifier(s)', 
                    'Confidence score']

intact_rows = [row.split('\t') for row in intact_raw_data.split('\n')]

# Create a pandas DataFrame from the list of rows and columns
intact_df = pd.DataFrame(intact_rows, columns=intact_columns)
intact_df.shape

(15, 15)

In [112]:
# # Cleaning up the dataframe

# filter out the columns that are needed
intact_df_filter = psicquic_df[['Unique identifier for interactor A', 
                                  'Unique identifier for interactor B', 
                                  'Interaction detection methods', 
                                  'First author', 
                                  'Identifier of the publication', 
                                  'Confidence score']]

# remove the last row
intact_df_filter = intact_df_filter[:-1]

# removing the uniprotkbID refix from the name
intact_df_filter[['Unique identifier for interactor A', 'Unique identifier for interactor B']] = intact_df_filter[['Unique identifier for interactor A', 'Unique identifier for interactor B']].map(lambda x: x.removeprefix('uniprotkb:'))

# apply the convert_protein_ID_name function to the first two rows
intact_df_filter[['Unique identifier for interactor A', 'Unique identifier for interactor B']] = intact_df_filter[['Unique identifier for interactor A', 'Unique identifier for interactor B']].map(convert_protein_ID_Name)

# removing duplicate rows
df_intact_dupl = intact_df_filter.drop_duplicates()

# rename the column headers, with prefix IntAct
df_intAct_final = df_intact_dupl.rename(columns= {'Unique identifier for interactor A': 'IntAct_interactor_a', 
                                        'Unique identifier for interactor B': 'IntAct_interactor_b',
                                        'Interaction detection methods': 'IntAct_method',
                                        'First author': 'IntAct_publication',
                                        'Identifier of the publication': 'IntAct_pubID',
                                        'Confidence score': 'IntAct_score'})

# get one column, only the interactor of the query
df_IntAct = get_interactors_for_target(df_intAct_final, 'IntAct_interactor_a', 'IntAct_interactor_b', query)

df_IntAct.head(5)

,IntAct_interactor_a,IntAct_interactor_b,IntAct_method,IntAct_publication,IntAct_pubID,IntAct_score,interactor_of_CADM4_HUMAN
0,HECA2_HUMAN,CADM4_HUMAN,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Huttlin et al. (2017),pubmed:28514442|doi:10.1038/nature22366|imex:I...,intact-miscore:0.35,HECA2_HUMAN
1,CD69_HUMAN,CADM4_HUMAN,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Huttlin et al. (2017),pubmed:28514442|doi:10.1038/nature22366|imex:I...,intact-miscore:0.35,CD69_HUMAN
2,CP2S1_HUMAN,CADM4_HUMAN,"psi-mi:""MI:0007""(anti tag coimmunoprecipitation)",Huttlin et al. (2017),pubmed:28514442|doi:10.1038/nature22366|imex:I...,intact-miscore:0.35,CP2S1_HUMAN
3,CD81_HUMAN,CADM4_HUMAN,"psi-mi:""MI:0006""(anti bait coimmunoprecipitation)",Palor et al. (2020),imex:IM-28053|pubmed:32900848,intact-miscore:0.35,CD81_HUMAN
7,CFTR_HUMAN,CADM4_HUMAN,"psi-mi:""MI:1314""(proximity-dependent biotin id...",Chevalier et al. (2022),imex:IM-29540|pubmed:36012204,intact-miscore:0.27,CFTR_HUMAN

In [34]:
# Extracting the data from the STRING-API

string_api_url = "https://string-db.org//api"

output_format = "json"
method = "interaction_partners"

string_request_url = "/".join([string_api_url, output_format, method])

params = {
    "identifiers": query,
    "species": 9606, # human
    "required_score": 0.2,
    "limit": 1000000 
}

response = requests.post(string_request_url, data = params)

string_raw_data = response.text

print(string_raw_data)

[{"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000222644", "preferredName_A": "CADM4", "preferredName_B": "MPP6", "ncbiTaxonId": 9606, "score": 0.888, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.045, "dscore": 0, "tscore": 0.888}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000357106", "preferredName_A": "CADM4", "preferredName_B": "CADM3", "ncbiTaxonId": 9606, "score": 0.862, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.128, "escore": 0, "dscore": 0, "tscore": 0.849}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000357110", "preferredName_A": "CADM4", "preferredName_B": "EPB41L2", "ncbiTaxonId": 9606, "score": 0.727, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.727}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000345259", "preferredName_A": "CADM4", "preferredName_B": "EPB41", "ncbiTaxonId": 9606, "score": 0.628, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.628}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000264638", "preferredName_A": "CADM4", "preferredName_B": "CNTNAP1", "ncbiTaxonId": 9606, "score": 0.61, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.084, "escore": 0, "dscore": 0, "tscore": 0.592}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000394794", "preferredName_A": "CADM4", "preferredName_B": "PTPN13", "ncbiTaxonId": 9606, "score": 0.578, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.578}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000381430", "preferredName_A": "CADM4", "preferredName_B": "MPP3", "ncbiTaxonId": 9606, "score": 0.538, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.072, "escore": 0.045, "dscore": 0, "tscore": 0.521}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000363480", "preferredName_A": "CADM4", "preferredName_B": "DLG3", "ncbiTaxonId": 9606, "score": 0.523, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.079, "escore": 0.049, "dscore": 0, "tscore": 0.499}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000287842", "preferredName_A": "CADM4", "preferredName_B": "NRG1", "ncbiTaxonId": 9606, "score": 0.518, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.518}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000384193", "preferredName_A": "CADM4", "preferredName_B": "CADM2", "ncbiTaxonId": 9606, "score": 0.5, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.109, "escore": 0, "dscore": 0, "tscore": 0.462}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000344786", "preferredName_A": "CADM4", "preferredName_B": "NFASC", "ncbiTaxonId": 9606, "score": 0.475, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.08, "escore": 0, "dscore": 0, "tscore": 0.453}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000363852", "preferredName_A": "CADM4", "preferredName_B": "SLC44A1", "ncbiTaxonId": 9606, "score": 0.474, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.474}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000390204", "preferredName_A": "CADM4", "preferredName_B": "HEPACAM2", "ncbiTaxonId": 9606, "score": 0.463, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.464, "dscore": 0, "tscore": 0}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000335196", "preferredName_A": "CADM4", "preferredName_B": "GLDN", "ncbiTaxonId": 9606, "score": 0.418, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.07, "escore": 0, "dscore": 0, "tscore": 0.4}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000469242", "preferredName_A": "CADM4", "preferredName_B": "SPTBN4", "ncbiTaxonId": 9606, "score": 0.413, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.138, "escore": 0, "dscore": 0, "tscore": 0.348}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000326018", "preferredName_A": "CADM4", "preferredName_B": "PRX", "ncbiTaxonId": 9606, "score": 0.401, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.062, "escore": 0.113, "dscore": 0, "tscore": 0.338}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000355771", "preferredName_A": "CADM4", "preferredName_B": "AFDN", "ncbiTaxonId": 9606, "score": 0.4, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.047, "escore": 0, "dscore": 0, "tscore": 0.397}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000361959", "preferredName_A": "CADM4", "preferredName_B": "CCN5", "ncbiTaxonId": 9606, "score": 0.398, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.399}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000420298", "preferredName_A": "CADM4", "preferredName_B": "CD200", "ncbiTaxonId": 9606, "score": 0.397, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.057, "escore": 0.125, "dscore": 0, "tscore": 0.328}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000342836", "preferredName_A": "CADM4", "preferredName_B": "OR6C74", "ncbiTaxonId": 9606, "score": 0.397, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.098, "dscore": 0, "tscore": 0.359}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000454623", "preferredName_A": "CADM4", "preferredName_B": "ITGAX", "ncbiTaxonId": 9606, "score": 0.388, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.071, "dscore": 0, "tscore": 0.368}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000480322", "preferredName_A": "CADM4", "preferredName_B": "CD99L2", "ncbiTaxonId": 9606, "score": 0.388, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.08, "escore": 0, "dscore": 0, "tscore": 0.363}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000312273", "preferredName_A": "CADM4", "preferredName_B": "LGI4", "ncbiTaxonId": 9606, "score": 0.386, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.12, "escore": 0, "dscore": 0, "tscore": 0.331}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000221891", "preferredName_A": "CADM4", "preferredName_B": "APLP1", "ncbiTaxonId": 9606, "score": 0.385, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.176, "escore": 0.145, "dscore": 0, "tscore": 0.197}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000362680", "preferredName_A": "CADM4", "preferredName_B": "SRC", "ncbiTaxonId": 9606, "score": 0.376, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.066, "escore": 0.102, "dscore": 0, "tscore": 0.316}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000287008", "preferredName_A": "CADM4", "preferredName_B": "PCDH1", "ncbiTaxonId": 9606, "score": 0.375, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.098, "escore": 0, "dscore": 0, "tscore": 0.336}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000228434", "preferredName_A": "CADM4", "preferredName_B": "CD69", "ncbiTaxonId": 9606, "score": 0.371, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.371, "dscore": 0, "tscore": 0}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000337168", "preferredName_A": "CADM4", "preferredName_B": "EPB41L1", "ncbiTaxonId": 9606, "score": 0.371, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.109, "escore": 0, "dscore": 0, "tscore": 0.324}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000368314", "preferredName_A": "CADM4", "preferredName_B": "NRCAM", "ncbiTaxonId": 9606, "score": 0.37, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.101, "escore": 0, "dscore": 0, "tscore": 0.329}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000481006", "preferredName_A": "CADM4", "preferredName_B": "PLP1", "ncbiTaxonId": 9606, "score": 0.367, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.138, "escore": 0.053, "dscore": 0, "tscore": 0.287}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000344819", "preferredName_A": "CADM4", "preferredName_B": "CMTM5", "ncbiTaxonId": 9606, "score": 0.366, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.151, "escore": 0, "dscore": 0, "tscore": 0.283}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000498662", "preferredName_A": "CADM4", "preferredName_B": "LRRC4B", "ncbiTaxonId": 9606, "score": 0.365, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.182, "escore": 0.095, "dscore": 0, "tscore": 0.211}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000219207", "preferredName_A": "CADM4", "preferredName_B": "PLLP", "ncbiTaxonId": 9606, "score": 0.364, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.048, "escore": 0, "dscore": 0, "tscore": 0.36}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000269571", "preferredName_A": "CADM4", "preferredName_B": "ERBB2", "ncbiTaxonId": 9606, "score": 0.363, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.363}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000447488", "preferredName_A": "CADM4", "preferredName_B": "LIN7A", "ncbiTaxonId": 9606, "score": 0.363, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.062, "escore": 0, "dscore": 0, "tscore": 0.349}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000370588", "preferredName_A": "CADM4", "preferredName_B": "CD99", "ncbiTaxonId": 9606, "score": 0.363, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.363}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000316861", "preferredName_A": "CADM4", "preferredName_B": "GPM6B", "ncbiTaxonId": 9606, "score": 0.357, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.086, "escore": 0.051, "dscore": 0, "tscore": 0.319}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000360214", "preferredName_A": "CADM4", "preferredName_B": "OPALIN", "ncbiTaxonId": 9606, "score": 0.356, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.109, "escore": 0, "dscore": 0, "tscore": 0.307}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000378635", "preferredName_A": "CADM4", "preferredName_B": "DRP2", "ncbiTaxonId": 9606, "score": 0.349, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.106, "escore": 0, "dscore": 0, "tscore": 0.302}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000264025", "preferredName_A": "CADM4", "preferredName_B": "NECTIN1", "ncbiTaxonId": 9606, "score": 0.349, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.067, "escore": 0.049, "dscore": 0, "tscore": 0.326}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000380948", "preferredName_A": "CADM4", "preferredName_B": "ITGB2", "ncbiTaxonId": 9606, "score": 0.349, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.349}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000265132", "preferredName_A": "CADM4", "preferredName_B": "AMBP", "ncbiTaxonId": 9606, "score": 0.344, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.102, "dscore": 0, "tscore": 0.299}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000380958", "preferredName_A": "CADM4", "preferredName_B": "MBP", "ncbiTaxonId": 9606, "score": 0.341, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.081, "escore": 0, "dscore": 0, "tscore": 0.311}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000380093", "preferredName_A": "CADM4", "preferredName_B": "SOX10", "ncbiTaxonId": 9606, "score": 0.334, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.154, "escore": 0, "dscore": 0, "tscore": 0.245}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000298251", "preferredName_A": "CADM4", "preferredName_B": "HEPACAM", "ncbiTaxonId": 9606, "score": 0.332, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.086, "escore": 0, "dscore": 0, "tscore": 0.3}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000421801", "preferredName_A": "CADM4", "preferredName_B": "HGFAC", "ncbiTaxonId": 9606, "score": 0.328, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.074, "escore": 0.296, "dscore": 0, "tscore": 0.052}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000362103", "preferredName_A": "CADM4", "preferredName_B": "POU3F1", "ncbiTaxonId": 9606, "score": 0.323, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.067, "escore": 0, "dscore": 0, "tscore": 0.305}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000225831", "preferredName_A": "CADM4", "preferredName_B": "CCL2", "ncbiTaxonId": 9606, "score": 0.323, "nscore": 0, "fscore": 0, "pscore": 0.282, "ascore": 0, "escore": 0.096, "dscore": 0, "tscore": 0}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000345359", "preferredName_A": "CADM4", "preferredName_B": "PODXL2", "ncbiTaxonId": 9606, "score": 0.321, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.139, "escore": 0.145, "dscore": 0, "tscore": 0.152}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000441858", "preferredName_A": "CADM4", "preferredName_B": "DMXL2", "ncbiTaxonId": 9606, "score": 0.32, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.32}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000365840", "preferredName_A": "CADM4", "preferredName_B": "ENTPD6", "ncbiTaxonId": 9606, "score": 0.318, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.074, "escore": 0, "dscore": 0, "tscore": 0.293}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000242480", "preferredName_A": "CADM4", "preferredName_B": "EGR2", "ncbiTaxonId": 9606, "score": 0.318, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.318}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000354778", "preferredName_A": "CADM4", "preferredName_B": "CNTNAP2", "ncbiTaxonId": 9606, "score": 0.318, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.044, "escore": 0, "dscore": 0, "tscore": 0.316}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000418070", "preferredName_A": "CADM4", "preferredName_B": "NECTIN3", "ncbiTaxonId": 9606, "score": 0.318, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.049, "dscore": 0, "tscore": 0.313}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000342114", "preferredName_A": "CADM4", "preferredName_B": "ICAM4", "ncbiTaxonId": 9606, "score": 0.318, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.318}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000228495", "preferredName_A": "CADM4", "preferredName_B": "KCTD10", "ncbiTaxonId": 9606, "score": 0.312, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.312}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000376048", "preferredName_A": "CADM4", "preferredName_B": "MAG", "ncbiTaxonId": 9606, "score": 0.304, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.188, "escore": 0, "dscore": 0, "tscore": 0.178}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000253496", "preferredName_A": "CADM4", "preferredName_B": "F12", "ncbiTaxonId": 9606, "score": 0.304, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.296, "dscore": 0, "tscore": 0.052}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000277903", "preferredName_A": "CADM4", "preferredName_B": "HABP2", "ncbiTaxonId": 9606, "score": 0.304, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.296, "dscore": 0, "tscore": 0.052}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000298925", "preferredName_A": "CADM4", "preferredName_B": "NELL1", "ncbiTaxonId": 9606, "score": 0.302, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.08, "escore": 0.113, "dscore": 0, "tscore": 0.213}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000363634", "preferredName_A": "CADM4", "preferredName_B": "TXNDC8", "ncbiTaxonId": 9606, "score": 0.301, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.301}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000296387", "preferredName_A": "CADM4", "preferredName_B": "CLDN19", "ncbiTaxonId": 9606, "score": 0.297, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.297}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000497691", "preferredName_A": "CADM4", "preferredName_B": "APLP2", "ncbiTaxonId": 9606, "score": 0.294, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.061, "escore": 0.145, "dscore": 0, "tscore": 0.192}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000343158", "preferredName_A": "CADM4", "preferredName_B": "EPB41L3", "ncbiTaxonId": 9606, "score": 0.292, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.066, "escore": 0, "dscore": 0, "tscore": 0.273}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000426503", "preferredName_A": "CADM4", "preferredName_B": "RNF4", "ncbiTaxonId": 9606, "score": 0.292, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.292, "dscore": 0, "tscore": 0}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000485112", "preferredName_A": "CADM4", "preferredName_B": "OR12D2", "ncbiTaxonId": 9606, "score": 0.29, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0.098, "dscore": 0, "tscore": 0.245}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000359634", "preferredName_A": "CADM4", "preferredName_B": "GOLGA7B", "ncbiTaxonId": 9606, "score": 0.289, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.105, "escore": 0, "dscore": 0, "tscore": 0.238}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000497806", "preferredName_A": "CADM4", "preferredName_B": "DLG4", "ncbiTaxonId": 9606, "score": 0.287, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.148, "escore": 0.049, "dscore": 0, "tscore": 0.191}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000480132", "preferredName_A": "CADM4", "preferredName_B": "NCAM1", "ncbiTaxonId": 9606, "score": 0.286, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.083, "escore": 0.126, "dscore": 0, "tscore": 0.181}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000314901", "preferredName_A": "CADM4", "preferredName_B": "LRRN1", "ncbiTaxonId": 9606, "score": 0.286, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.063, "escore": 0.095, "dscore": 0, "tscore": 0.226}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000252483", "preferredName_A": "CADM4", "preferredName_B": "NECTIN2", "ncbiTaxonId": 9606, "score": 0.284, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.042, "escore": 0, "dscore": 0, "tscore": 0.284}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000402060", "preferredName_A": "CADM4", "preferredName_B": "PVR", "ncbiTaxonId": 9606, "score": 0.279, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.279}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000455469", "preferredName_A": "CADM4", "preferredName_B": "GJE1", "ncbiTaxonId": 9606, "score": 0.279, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0, "escore": 0, "dscore": 0, "tscore": 0.279}, {"stringId_A": "9606.ENSP00000222374", "stringId_B": "9606.ENSP00000384887", "preferredName_A": "CADM4", "preferredName_B": "CEACAM19", "ncbiTaxonId": 9606, "score": 0.278, "nscore": 0, "fscore": 0, "pscore": 0, "ascore": 0.045, "escore": 0, "dscore": 0, "tscore": 0.275}, {"stringId_A": "9606.ENSP00000222374", "

In [35]:
# Getting the STRING-API data into a pandas df
string_df = pd.read_json(string_raw_data)
string_df.head(5)

/tmp/ipykernel_231037/906031186.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  string_df = pd.read_json(string_raw_data)

,stringId_A,stringId_B,preferredName_A,preferredName_B,ncbiTaxonId,score,nscore,fscore,pscore,ascore,escore,dscore,tscore
0,9606.ENSP00000222374,9606.ENSP00000222644,CADM4,MPP6,9606,0.888,0,0.0,0.0,0.000,0.045,0,0.888
1,9606.ENSP00000222374,9606.ENSP00000357106,CADM4,CADM3,9606,0.862,0,0.0,0.0,0.128,0.000,0,0.849
2,9606.ENSP00000222374,9606.ENSP00000357110,CADM4,EPB41L2,9606,0.727,0,0.0,0.0,0.000,0.000,0,0.727
3,9606.ENSP00000222374,9606.ENSP00000345259,CADM4,EPB41,9606,0.628,0,0.0,0.0,0.000,0.000,0,0.628
4,9606.ENSP00000222374,9606.ENSP00000264638,CADM4,CNTNAP1,9606,0.610,0,0.0,0.0,0.084,0.000,0,0.592

In [113]:
# Cleaning up the string dataframe

# filter out the columns that are needed
string_df_filter = string_df[[  'preferredName_A', 
                                'preferredName_B', 
                                'score', 
                                'escore']]

# adding 'HUMAN' afterfix to the column values
def add_suffix_human(value):
    return value + '_HUMAN'

string_df_filter[['preferredName_A', 'preferredName_B']] = string_df_filter[['preferredName_A', 'preferredName_B']].apply(add_suffix_human)


# renaming column headers
df_string_final = string_df_filter.rename(columns= {'preferredName_A': 'string_interactor_a', 
                                                    'preferredName_B': 'string_interactor_b',
                                                    'score': 'string_score',
                                                    'escore': 'string_escore'})

# get one column, only the interactor of the query
df_string = get_interactors_for_target(df_string_final, 'string_interactor_a', 'string_interactor_b', query)

df_string.head(5)

/tmp/ipykernel_231037/2941665265.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  string_df_filter[['preferredName_A', 'preferredName_B']] = string_df_filter[['preferredName_A', 'preferredName_B']].apply(add_suffix_human)

,string_interactor_a,string_interactor_b,string_score,string_escore,interactor_of_CADM4_HUMAN
0,CADM4_HUMAN,MPP6_HUMAN,0.888,0.045,MPP6_HUMAN
1,CADM4_HUMAN,CADM3_HUMAN,0.862,0.000,CADM3_HUMAN
2,CADM4_HUMAN,EPB41L2_HUMAN,0.727,0.000,EPB41L2_HUMAN
3,CADM4_HUMAN,EPB41_HUMAN,0.628,0.000,EPB41_HUMAN
4,CADM4_HUMAN,CNTNAP1_HUMAN,0.610,0.000,CNTNAP1_HUMAN

In [68]:
# GETTING THE DATA FROM the HIPPIE-API

hippie_api_url = "http://cbdm-01.zdv.uni-mainz.de/~mschaefer/hippie/queryHIPPIE.php"

protein_to_query = "CADM4"
layer = 1 #to query protein within input set (0) or against all HIPPIE proteins (1, default)
threshold = 0 #confidence threshold, default is 0
format = "conc_file" #this generates a tab seperated text file (other interesting input types: "mitab", "browser")

hippie_request_url = f"{hippie_api_url}?proteins={protein_to_query}&layers={layer}&conf_thres={threshold}&out_type={format}"

hippie_response = requests.get(hippie_request_url).text

print(hippie_response)

print(hippie_request_url)

# there seems to be an issue with the PHP request response, probably the server is not correctly configured

<?php

$url = "http" . (isset($_SERVER["HTTPS"]) ? "s" : "") . "://" . "{$_SERVER['HTTP_HOST']}/{$_SERVER['REQUEST_URI']}";

$parts = parse_url($url);
parse_str($parts['query'], $query);

$out_type = empty($query['out_type']) ? "conc_file" : $query['out_type'];
$query_genes = empty($query['proteins']) ? "" : str_replace(array(",", ";", "|"), PHP_EOL, $query['proteins']);
$layers = empty($query['layers']) ? 1 : $query['layers'];
$layers = $query['layers']=='0' ? 0 : $layers;
$conf_thres = empty($query['conf_thres']) ? 0 : $query['conf_thres'];

echo '<html>
         <form action="fast_query_tissue.php" method="POST" id="netQuery">
            <input type="hidden" name="out_type" value="'.$out_type.'" />
            <input type="hidden" name="query_genes" value="'.$query_genes.'" />
            <input type="hidden" name="layers" value='.$layers.' />
            <input type="hidden" name="conf_thres" value='.$conf_thres.' />
         </form>
         <script type="text/javascript">
            netQuery.submit();
         </script>
      </html>';

?>

http://cbdm-01.zdv.uni-mainz.de/~mschaefer/hippie/queryHIPPIE.php?proteins=CADM4&layers=1&conf_thres=0&out_type=conc_file

In [72]:
## !!!!! HIPPIE website seems to be down at the moment

# GETTING THE DATA FROM HIPPIE through WEBSCRAPING
import requests
import json
import re
from bs4 import BeautifulSoup

protein = query

url = "http://cbdm-01.zdv.uni-mainz.de/~mschaefer/hippie/query.php?s="+str(protein)

payload = {}
headers = {
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7', 
'Accept-Language': 'nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,fr;q=0.6' ,
'Connection': 'keep-alive', 
'Referer': 'http://cbdm-01.zdv.uni-mainz.de/~mschaefer/hippie/',
'Upgrade-Insecure-Requests': '1' ,
'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Mobile Safari/537.36' 
}

response = requests.request("GET", url, headers=headers, data=payload)
soup = BeautifulSoup(response.text, "html.parser")
table = soup.find('tbody') # already skipped the columns names

rows = table.find_all('tr')

interactions = []
for idx, row in enumerate(rows):
    data = row.find_all("td")
    interaction = {
    "Interactor": data[0].text,
    "EntrezGeneID": data[1].text,
    "GeneSymbol": data[2].text,
    "Score": data[3].text
    }
    interactions.append(interaction) 
   

print(rows)

[<tr><td>".$int-&gt;getLinkFormattedUniprotIDOfInteractor2()."</td><td>".$int-&gt;getLinkFormattedEntrezIDOfInteractor2()."</td><td>"
                     .$int-&gt;getNamesOfInteractor2()."</td><td><a "&i1="$int-" echo="" entrez'){="" href='details.php?q=$int-&gt;dbId";
                     if($type == '>entrezGeneId1&amp;i2=".$int-&gt;entrezGeneId2[0]."&amp;t=e";
                     }
                     elseif($type == 'uniprot'){
                        echo "&amp;i1=$int-&gt;uniprotId1&amp;i2=$int-&gt;uniprotId2&amp;t=u";
                     }
                     echo "'&gt;".$int-&gt;score."</a></td>";
                     echo "<td><a href='query.php?s=".$int-&gt;uniprotId2."'>Show</a></td></tr>]

In [77]:
# GETTING THE DATA FROM THE APID db by WEBSCRAPING

import requests
import json
import re
from bs4 import BeautifulSoup


#Function gets protein id from name value. (Example: VCAM1_HUMAN -> P19320). We will need this protein ID to generate our table.
def extract_protein_id(name):
    url = "http://cicblade.dep.usal.es:8080/APID/searchProtein.action" # Endpoint to search for protein by name

    payload = 'proteinName='+str(name)+'&taxon=0'
    headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Language': 'en-US,en;q=0.9',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'application/x-www-form-urlencoded',
    'Cookie': 'JSESSIONID=086030D12C94A8248DA2B5B9A84C16FA; _ga=GA1.2.581619552.1696441740; _gid=GA1.2.818200239.1696441740; _gat=1; _ga_7JSDHY18SK=GS1.2.1696441740.1.1.1696443448.0.0.0',
    'Origin': 'http://cicblade.dep.usal.es:8080',
    'Referer': 'http://cicblade.dep.usal.es:8080/APID/init.action',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'
    }

    response = requests.request("POST", url, headers=headers, data=payload) # Execute HTTP request, response is stored in 'response'
    soup = BeautifulSoup(response.text, "html.parser") #Parse response.text (which is HTML) with a HTML parser
    table = soup.find('table', id="proteins") #use soup.find function to find a table in the HTML with id "proteins" (You can get this value by checking the HTML in the response from your HTTP request above. Hardcoded it to "proteins" because this will not change.)
    row = table.find_next('td') #use the beautifulsoup library again to find a html element in the found table. (Give me the first column value.)
    
    return row.text # row.text gives us the protein ID, we will need this protein ID to generate our table. (Example: VCAM1_HUMAN -> P19320)


def extract_table(proteinid):
    url = "http://cicblade.dep.usal.es:8080/APID/InteractionsGrid.action?protein1="+str(proteinid)+"&protein2=NA"

    payload = {}
    headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'Accept-Language': 'en-US,en;q=0.9',
    'Connection': 'keep-alive',
    'Cookie': 'JSESSIONID=086030D12C94A8248DA2B5B9A84C16FA; _ga=GA1.2.581619552.1696441740; _gid=GA1.2.818200239.1696441740; _ga_7JSDHY18SK=GS1.2.1696441740.1.1.1696442421.0.0.0',
    'Referer': 'http://cicblade.dep.usal.es:8080/APID/searchProtein.action',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36'
    }

    response = requests.request("GET", url, headers=headers, data=payload)
    soup = BeautifulSoup(response.text, "html.parser")
    table = soup.find('table', id="interactions") #Find the table

    rows = table.find_all("tr") # Find all table rows
    interactions = [] #initialize empty list
    for idx, row in enumerate(rows): #loop over rows, keep index
        if idx == 0: # first row is the header, skip.
            pass
        else:
            try:
                data1 = row.find_all("td") # get column
                interaction = { # build intraction object
                "ProteinA": data1[0].get_text().strip(),
                "ProteinB": data1[1].get_text().strip(),
                "MethodType": data1[2].get_text().strip(),
                "Method": data1[3].get_text().strip(),
                "Publication": re.sub(' +', ' ',data1[4].get_text().strip().replace("\n", "")),
                "Source": data1[5].get_text().strip()
                }
                interactions.append(interaction) #append interaction object to result list
            except:
                pass
    return interactions #return the result list


proteinid = extract_protein_id(query)
apid_results = extract_table(proteinid)
# print(json.dumps(apid_results, indent=4))
print(apid_results)

[{'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'KC1E_HUMAN', 'MethodType': 'binary', 'Method': 'two hybrid (MI:0018)', 'Publication': 'Vinayagam, A. et al., 2011 (PMID:21900206 )', 'Source': 'IntAct (Acc: EBI-7129549  )'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'KC1E_HUMAN', 'MethodType': 'binary', 'Method': 'two hybrid (MI:0018)', 'Publication': 'Vinayagam, A. et al., 2011 (PMID:21900206 )', 'Source': 'BioGRID (Acc: 600990  )'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'DC1I1_HUMAN', 'MethodType': 'binary', 'Method': 'two hybrid (MI:0018)', 'Publication': 'Vinayagam, A. et al., 2011 (PMID:21900206 )', 'Source': 'IntAct (Acc: EBI-7145902  )'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'DC1I1_HUMAN', 'MethodType': 'binary', 'Method': 'two hybrid (MI:0018)', 'Publication': 'Vinayagam, A. et al., 2011 (PMID:21900206 )', 'Source': 'BioGRID (Acc: 601286  )'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'ACTS_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'DPP9_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'DIP2A_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'BMR1A_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'NMT2_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'MPP7_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': '2ABB_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CADM4_HUMAN', 'ProteinB': 'DEN6A_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CD81_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'anti bait coimmunoprecipitation (MI:0006)', 'Publication': 'Palor, M. et al., 2020 (PMID:32900848 )', 'Source': 'IntAct (Acc: EBI-25645944  )'}, {'ProteinA': 'CD81_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'anti bait coimmunoprecipitation (MI:0006)', 'Publication': 'Palor, M. et al., 2020 (PMID:32900848 )', 'Source': 'IntAct (Acc: EBI-25646004  )'}, {'ProteinA': 'CD81_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'anti bait coimmunoprecipitation (MI:0006)', 'Publication': 'Palor, M. et al., 2020 (PMID:32900848 )', 'Source': 'IntAct (Acc: EBI-25646019  )'}, {'ProteinA': 'CD81_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'anti bait coimmunoprecipitation (MI:0006)', 'Publication': 'Palor, M. et al., 2020 (PMID:32900848 )', 'Source': 'IntAct (Acc: EBI-25646036  )'}, {'ProteinA': 'CD69_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'anti tag coimmunoprecipitation (MI:0007)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'IntAct (Acc: EBI-21551241  )'}, {'ProteinA': 'CD69_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioGRID (Acc: 2269448  )'}, {'ProteinA': 'CD69_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CP2S1_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'anti tag coimmunoprecipitation (MI:0007)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'IntAct (Acc: EBI-21623270  )'}, {'ProteinA': 'CP2S1_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioGRID (Acc: 2232293  )'}, {'ProteinA': 'CP2S1_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'HECA2_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'anti tag coimmunoprecipitation (MI:0007)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'IntAct (Acc: EBI-21700110  )'}, {'ProteinA': 'HECA2_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2015 (PMID:26186194 )', 'Source': 'BioGRID (Acc: 1196008  )'}, {'ProteinA': 'HECA2_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioGRID (Acc: 2257453  )'}, {'ProteinA': 'HECA2_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'RNF4_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Kumar, R. et al., 2017 (PMID:29180619 )', 'Source': 'BioGRID (Acc: 2494593  )'}, {'ProteinA': 'RASN_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'proximity labelling technology (MI:1313)', 'Publication': 'Kovalski, JR. et al., 2019 (PMID:30639242 )', 'Source': 'BioGRID (Acc: 2548673  )'}, {'ProteinA': 'CNKR1_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'NotAssigned', 'Method': 'in vivo (MI:0493)', 'Publication': 'Giallourakis, C. et al., 2006 (PMID:16825666 )', 'Source': 'HPRD (Acc: Q8NFZ8  )'}, {'ProteinA': 'EPHB6_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'GPAT1_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'RF1M_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CLC4A_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'CERS2_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'RISC_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'NR2F6_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'HBG2_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}, {'ProteinA': 'TSN16_HUMAN', 'ProteinB': 'CADM4_HUMAN', 'MethodType': 'indirect', 'Method': 'affinity chromatography technology (MI:0004)', 'Publication': 'Huttlin, EL. et al., 2017 (PMID:28514442 )', 'Source': 'BioPlex'}]

In [114]:
# Getting the data from APID into a df

apid_df = pd.DataFrame(apid_results)

# filter out the columns that are needed
apid_df_filter = apid_df[[  'ProteinA', 
                                'ProteinB', 
                                'Method', 
                                'Publication',
                                'Source']]

# renaming column headers
df_apid_final = apid_df_filter.rename(columns= {'ProteinA': 'apid_interactor_a', 
                                                    'ProteinB': 'apid_interactor_b',
                                                    'Method': 'apid_method',
                                                    'Publication': 'apid_publication',
                                                    'Source': 'apid_source'})

# get one column, only the interactor of the query
df_apid = get_interactors_for_target(df_apid_final, 'apid_interactor_a', 'apid_interactor_b', query)

df_apid.head(5)

,apid_interactor_a,apid_interactor_b,apid_method,apid_publication,apid_source,interactor_of_CADM4_HUMAN
0,CADM4_HUMAN,KC1E_HUMAN,two hybrid (MI:0018),"Vinayagam, A. et al., 2011 (PMID:21900206 )",IntAct (Acc: EBI-7129549 ),KC1E_HUMAN
1,CADM4_HUMAN,KC1E_HUMAN,two hybrid (MI:0018),"Vinayagam, A. et al., 2011 (PMID:21900206 )",BioGRID (Acc: 600990 ),KC1E_HUMAN
2,CADM4_HUMAN,DC1I1_HUMAN,two hybrid (MI:0018),"Vinayagam, A. et al., 2011 (PMID:21900206 )",IntAct (Acc: EBI-7145902 ),DC1I1_HUMAN
3,CADM4_HUMAN,DC1I1_HUMAN,two hybrid (MI:0018),"Vinayagam, A. et al., 2011 (PMID:21900206 )",BioGRID (Acc: 601286 ),DC1I1_HUMAN
4,CADM4_HUMAN,ACTS_HUMAN,affinity chromatography technology (MI:0004),"Huttlin, EL. et al., 2017 (PMID:28514442 )",BioPlex,ACTS_HUMAN

In [ ]:
# Make an intersecions diagram using the pyUpSet to check the interactors of VCAM1 
from upsetplot import UpSet